### ISSUE TITLE
Input Names

### ISSUE THREAD

**Issue by lenichols** [jplehmann/timecalc#7]
What is the best way to iterate textfield names? I need to send data from the calculator to a MySQL database.

**Comment by jplehmann** [comment]
I don't really understand what you are asking, but you should have access
to the whole model and all the fields in Javascript.  You can see here how
I iterate over the rows to compute a total.

https://github.com/jplehmann/timecalc/blob/master/src/timecalc.js#L26

**Comment by lenichols** [comment]
its ok... i iterated through the fields and appended the names. My issues was each row was producing fields with the same names so when i send to mysql it was hard to get the post values. Thanks for your help anyways!
