### ISSUE TITLE
Adding an OnClick event to populate a new row

### ISSUE THREAD

**Issue by lenichols** [jplehmann/timecalc#8]
What is your advice on how to add an onClick event to add a new table row?

I tried:

```
self.initNewRow = function () {
      self.addRow();
    };
    
  $('#toTop').click(function(){
    self.initNewRow();
  });
```

But self.initNewRow isnt being called... instead I get an error (self.initNewRow) is not a function.

I added this init function to the:

`function TimeSheetModel(options) `

function. Any advice on how to call "addRow" properly would be helpful. Thanks in advance.

**Comment by jplehmann** [comment]
Hi @lenichols, sorry that I do not have time to provide this level of support right now, and can't remember much about it off the top of my head (nor have I used knockout in several years).  My only thought is that if you want any row clickable you'll need unique IDs. They have pretty good documentation though.
